### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by JasonGross** [bmsherman/topology#1]
I'd like to get this on the Coq benchmarking list.  To do that, there needs to be an opam package.  To put this on opam, there needs to be a license; can you add an appropriate LICENSE file to the root of the repo, on both the master branch and the predicative?  (Easy templates to use are available [here](https://choosealicense.com/).)

**Comment by bmsherman** [comment]
I added an MIT license to both master and predicative branches. Thanks!
