### ISSUE TITLE
Neither master nor predicative branches build (with v8.6, nor with trunk)

### ISSUE THREAD

**Issue by JasonGross** [bmsherman/topology#10]
See [predicative v8.6 logs](https://travis-ci.org/JasonGross/topology/jobs/225795842), [predicative trunk logs](https://travis-ci.org/JasonGross/topology/jobs/225795843), [master v8.6 logs](https://travis-ci.org/JasonGross/topology/jobs/225795868), and [master trunk logs](https://travis-ci.org/JasonGross/topology/jobs/225795869).  The error messages are:
On master:
```
COQC src/FormTopC/FormalSpace.v
<unknown>
Error: Attempt to save an incomplete proof (in proof refl)
```
```
File "./src/FormTopC/Metric.v", line 526, characters 0-47:
Error: The "clear implicits" flag is incompatible with implicit annotations
Command exited with non-zero status 1
```
On predicative:
```
File "./src/Algebra/SetsC.v", line 169, characters 46-55:
Error: Universes {Prob.Algebra.SetsC.559 Prob.Algebra.SetsC.558} are unbound.
Command exited with non-zero status 1
```

**Comment by bmsherman** [comment]
I have now renamed some branches. "predicative" is now "master", and "master" is now "master-old". I'm only planning on keeping "master" up to date. I've now modified the "master" branch so that it works on both v8.6 and trunk.
