### ISSUE TITLE
`cofix` tactic without a name is deprecated

### ISSUE THREAD

**Issue by ejgallego** [bmsherman/topology#18]
The tactic form cofix. without a name is deprecated as it depends on the name of the current lemma.

See coq/coq#7196.

The backwards compatible fix is to use cofix name_of_the_fixpoint. Problematic entry:
```
src/FormTopC/NatInfty.v:182:generalize dependent n. cofix.
```

**Comment by ppedrot** [comment]
This bug should be closed.
